const staticPath = "/static/images";

const fileNames = {
  ALTERNATE_FORMAT_CONVERSION: `${staticPath}/alternate-format-conversion.svg`,
  MENTOR_CONNECT: `${staticPath}/mentor-connect.svg`,
  VIDEO_AND_AUDIO_CAPTIONING: `${staticPath}/video-and-audio-captioning.svg`,
  VOLUNTEER_CONNECT: `${staticPath}/volunteer-connect.svg`,
  TRAINING: `${staticPath}/training.svg`,
  STATUS_IMAGE_AFC: `${staticPath}/status-image-afc.svg`,
  STATUS_IMAGE_VC: `${staticPath}/status-image-vc.svg`,
  AUTH_BACKGROUND_IMAGE: `${staticPath}/splashvector.svg`,
  LIP_LOGO: `${staticPath}/logo.svg`,
  REGISTRATION_SUCCESS_IMAGE: `${staticPath}/vsplash.svg`,
  ALTERNATE_FORMAT_CONVERSION_SPLASH: `${staticPath}/alternate-format-conversion-splash.svg`,
  FAILURE_ALERT_ICON: `${staticPath}/failure-alert-icon.svg`,
  SUCCESS_ALERT_ICON: `${staticPath}/success-alert-icon.svg`,
  WEBINARS: `${staticPath}/webinars.svg`,
  MENTORSHIP: `${staticPath}/mentorship.svg`,
  JOB_OPPORTUNITIES: `${staticPath}/job-opportunities.svg`,
  LEARNING_HUB: `${staticPath}/learning-hub.svg`,
  SERVICE_LOCK: `${staticPath}/lock.svg`,
  STUDENTS: `${staticPath}/students.svg`,
  ONBOARD_STUDENTS: `${staticPath}/onboard-students.svg`,
  ONBOARD_STAFF: `${staticPath}/onboard-staff.svg`,
  CLOSE_ICON: `${staticPath}/closeIcon.svg`,
  IMPORT_STUDENTS_SAMPLE: `${staticPath}/IMPORT_STUDENTS_SAMPLE.csv`,
  VECTOR_UP: `${staticPath}/vector-up.svg`,
  VECTOR_DOWN: `${staticPath}/vector-down.svg`,
  INFO_ICON: `${staticPath}/info-icon.svg`,
  MENTORSHIP_DESC: `${staticPath}/mentorship-desc.svg`,
  JOB_DESC: `${staticPath}/job-desc.svg`,
  HACKER: `${staticPath}/hacker.svg`,
  HACKATHON_DESC: `${staticPath}/hackathon.png`,
  MESSAGE_ICON: `${staticPath}/message.svg`,
  MESSAGE_CIRCLE: `${staticPath}/message-circle.svg`,
};

export default fileNames;
