export enum ColorThemes {
  BLACKWHITE = "BLACKWHITE",
  WHITEBLACK = "WHITEBLACK",
  GREENWHITE = "GREENWHITE",
  REDWHITE = "REDWHITE",
  YELLOWBLACK = "YELLOWBLACK",
  YELLOWBLUE = "YELLOWBLUE",
}
export enum FontThemes {
  FONTM = "FONTM",
  FONTL = "FONTL",
  FONTXL = "FONTXL",
}
