export enum UniversityStatus {
  REGISTRATION_PENDING = "REGISTRATION_PENDING",
  REGISTRATION_COMPLETE = "REGISTRATION_COMPLETE",
  REGISTRATION_REJECTED = "REGISTRATION_REJECTED",
  APPROVAL_PENDING = "APPROVAL_PENDING",
}
